import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/ui/Navbar/Navbar";
import SignOutLinks from "@/components/Signout/SignOutLinks";
import { Toaster } from "@/components/ui/sonner"
import SignInLinks from "@/components/SignIn/SignInLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          
          {children}
          <Toaster />
          <SignInLinks />
          <SignOutLinks />
        </body>
      </html>
    </ClerkProvider>

  );
}
